### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by ghost** [Xedart/KNURE-TimeTable#1]
Project not builds due to:
- 'AsyncDisplayKit/AsyncDisplayKit.h' file not found
- failed to import bridging header '/Users/alexkovalov/Downloads/KNURE-TimeTable-ASDK_MAIN/KNURE TimeTable/KNURE TimeTable-Bridging-Header.h'

Steps to reproduce: 
1. download project as zip
2. open 
3. build

**Comment by Xedart** [comment]
Ok I fixed that. You can download runnable protect in current main branch. 
Notice that project is under developing.
IMPORTANT: current version works with IPAD only.
